name: branch-build
on:
  push:
    branches-ignore:
      - dev
      - master
      - 'version-increment-*'
jobs:
  compile-codebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
            package-lock.json
          key: ${{ runner.os }}-branch-${{ hashFiles('**/package-lock.json') }}
      - run: npm install --production=false --loglevel notice --legacy-peer-deps
      - run: npm run lint
      - run: npm run build-docker
